name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x, 1.17.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: make test
  ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake
